import pygame
import time
print("Chargement des images...")

pygame.init()
pygame.display.set_caption("Le Babelcasino")
largeur, hauteur = 400, 400
fenetre = pygame.display.set_mode((largeur, hauteur))
chargement = [pygame.image.load(f'images/Fonds d\'ecran/Chargement/c{i}.png').convert() for i in range(1,12)]
fenetre.blit(chargement[0], (0, 0))  # Afficher le fond
pygame.display.flip()  # Mettre à jour l'affichage

time.sleep(3)

souris = pygame.image.load('images/curseur.cur').convert_alpha()
fond = pygame.image.load('images/Fonds d\'ecran/Croupier2.png').convert()
chute = [pygame.image.load(f'images/Jeu de combat/Fonds/Chute/_a_frm{i},100.png') for i in range(4)]
eglise = [pygame.image.load(f'images/Jeu de combat/Fonds/Eglise/_a_frm{i},150.png') for i in range(8)]
pluie = [pygame.image.load(f'images/Jeu de combat/Fonds/Pluie/_a_frm{i},120.png') for i in range(8)]
lave = [pygame.image.load(f'images/Jeu de combat/Fonds/Lave/_a_frm{i},100.png') for i in range(8)]
temple = [pygame.image.load(f'images/Jeu de combat/Fonds/Temple/_a_frm{i},100.png') for i in range(8)]
desert = [pygame.image.load(f'images/Jeu de combat/Fonds/Desert/_a_frm{i},80.png') for i in range(8)]
fond3 = pygame.image.load('images/Fonds d\'ecran/enfer2.png').convert()
roulette = pygame.image.load('images/roulette2.png').convert_alpha()
roulette2 = pygame.image.load('images/roulette3.png').convert_alpha()
diable = pygame.image.load('images/Diable.png').convert_alpha()
entrer = pygame.image.load('images/Entrer-1.png').convert_alpha()
entrer2 = pygame.image.load('images/Entrer-2.png').convert_alpha()
retour = pygame.image.load('images/Retour-1.png').convert_alpha()
retour2 = pygame.image.load('images/Retour-2.png').convert_alpha()
imgpof = pygame.image.load('images/pof1.png').convert_alpha()
imgpof2 = pygame.image.load('images/pof2.png').convert_alpha()
machine_a_sous2 = pygame.image.load('images/machine_a_sous2.png').convert_alpha()
machine_a_sous1 = pygame.image.load('images/machine_a_sous1.png').convert_alpha()
blackjack2 = pygame.image.load('images/blackjack2.png').convert_alpha()
blackjack1 = pygame.image.load('images/blackjack1.png').convert_alpha()
face = pygame.image.load('Pile_ou_face/Piece face.png').convert_alpha()
pile = pygame.image.load('Pile_ou_face/Piece pile.png').convert_alpha()
face2 = pygame.image.load('Pile_ou_face/Piece face2.png').convert_alpha()
pile2 = pygame.image.load('Pile_ou_face/Piece pile2.png').convert_alpha()
icone = pygame.image.load('images/icone.png').convert_alpha()
paradis = pygame.image.load('images/Fonds d\'ecran/paradis.png').convert_alpha()
fleche_retour = pygame.image.load('images/Fleche_retour.png').convert_alpha()
fleche_retour2 = pygame.image.load('images/Fleche_retour2.png').convert_alpha()
bouton_play_bj = pygame.image.load('images/BoutonPlay1.png').convert_alpha()
bouton_play_bj2 = pygame.image.load('images/BoutonPlay2.png').convert_alpha()
bouton_stop_bj = pygame.image.load('images/BoutonStop1.png').convert_alpha()
bouton_stop_bj2 = pygame.image.load('images/BoutonStop2.png').convert_alpha()
maskot = pygame.image.load('images/maskot.png').convert_alpha()
fondbj = pygame.image.load('images/Fonds d\'ecran/fondbj.png').convert_alpha()
abel = pygame.image.load('images/abel.png').convert_alpha()
boutique1 = pygame.image.load('images/boutique1.png').convert_alpha()
boutique2 = pygame.image.load('images/boutique2.png').convert_alpha()
jeucombat1 = pygame.image.load('images/Jeu_combat3.png').convert_alpha()
jeucombat2 = pygame.image.load('images/Jeu_combat4.png').convert_alpha()
vodka1 = pygame.image.load('images/vodka1.png').convert_alpha()
vodka2 = pygame.image.load('images/Vodka2.png').convert_alpha()
alcool1 = pygame.image.load('images/Alcool1.png').convert_alpha()
alcool2 = pygame.image.load('images/Alcool2.png').convert_alpha()
whisky1 = pygame.image.load('images/Whisky1.png').convert_alpha()
whisky2 = pygame.image.load('images/Whisky2.png').convert_alpha()
mojito1 = pygame.image.load('images/Mojito1.png').convert_alpha()
mojito2 = pygame.image.load('images/Mojito2.png').convert_alpha()
biere1 = pygame.image.load('images/Bière1.png').convert_alpha()
biere2 = pygame.image.load('images/Bière2.png').convert_alpha()
effet_vodka = pygame.image.load('images/Caractéristiques/tab_vodka.png').convert_alpha()
effet_biere = pygame.image.load('images/Caractéristiques/tab_biere.png').convert_alpha()
effet_whisky = pygame.image.load('images/Caractéristiques/tab_whisky.png').convert_alpha()
effet_mojito = pygame.image.load('images/Caractéristiques/tab_mojito.png').convert_alpha()
icone_klaxon = pygame.image.load('images/icone_klaxon.png').convert_alpha()
icone_cryoblade = pygame.image.load('images/icone_cryoblade.png').convert_alpha()
icone_maehv = pygame.image.load('images/icone_maevh.png').convert_alpha()
icone_zendo = pygame.image.load('images/icone_zendo.png').convert_alpha()
icone_zukong = pygame.image.load('images/icone_zukong.png').convert_alpha()
icone_hero = pygame.image.load('images/icone_hero.png').convert_alpha()
icone_hsuku = pygame.image.load('images/icone_hsuku.png').convert_alpha()
icone_whistler = pygame.image.load('images/icones_whistler.png').convert_alpha()
icone_sanguinar = pygame.image.load('images/icone_sanguinar.png').convert_alpha()
icone_tethermancer = pygame.image.load('images/icone_tether.png').convert_alpha()
icone_twilight = pygame.image.load('images/icone_twilight.png').convert_alpha()
icone_pureblade = pygame.image.load('images/icone_pureblade.png').convert_alpha()
icone_aether = pygame.image.load('images/icone_aether.png').convert_alpha()
icone_suzumebachi = pygame.image.load('images/icone_suzumebachi.png').convert_alpha()
icone_yggdra = pygame.image.load('images/icone_yggdra.png').convert_alpha()
icone_dusk = pygame.image.load('images/icone_dusk.png').convert_alpha()
info1 = pygame.image.load('images/Jeu de Combat/Infos/Info.png').convert_alpha()
info2 = pygame.image.load('images/Jeu de Combat/Infos/Info2.png').convert_alpha()
valider = pygame.image.load("images/Jeu de combat/valider.png").convert_alpha()
img_hero = pygame.image.load('images/Btn_heros/_a_frm0,70.png').convert_alpha()
item_img_biere = pygame.image.load('images/Inventaire/Biere.png').convert_alpha()
item_img_whisky = pygame.image.load('images/Inventaire/Whisky.png').convert_alpha()
item_img_mojito = pygame.image.load('images/Inventaire/Mojito.png').convert_alpha()
backpack1 = pygame.image.load('images/Inventaire/Backpack1.png').convert_alpha()
backpack2 = pygame.image.load('images/Inventaire/Backpack2.png').convert_alpha()
valider1 = pygame.image.load('images/Inventaire/valider1.png').convert_alpha()
valider2 = pygame.image.load('images/Inventaire/valider2.png').convert_alpha()
select1 = pygame.image.load('images/select1.png').convert_alpha()
select2 = pygame.image.load('images/select2.png').convert_alpha()
flecheretour1 = pygame.image.load('images/Inventaire/retourr1.png').convert_alpha()
flecheretour2 = pygame.image.load('images/Inventaire/retourr2.png').convert_alpha()
banniere = pygame.image.load('images/Inventaire/Bannière.png').convert_alpha()

pygame.display.set_icon(icone)