import pygame

pygame.init()
pygame.display.set_caption("Le Babelcasino")
largeur, hauteur = 400, 400

fenetre = pygame.display.set_mode((largeur, hauteur))
fond = pygame.image.load('images/Fonds d\'ecran/Croupier2.png').convert()
fond3 = pygame.image.load('images/Fonds d\'ecran/enfer2.png').convert()
roulette = pygame.image.load('images/roulette2.png').convert_alpha()
roulette2 = pygame.image.load('images/roulette3.png').convert_alpha()
diable = pygame.image.load('images/Diable.png').convert_alpha()
entrer = pygame.image.load('images/Entrer-1.png').convert_alpha()
entrer2 = pygame.image.load('images/Entrer-2.png').convert_alpha()
retour = pygame.image.load('images/Retour-1.png').convert_alpha()
retour2 = pygame.image.load('images/Retour-2.png').convert_alpha()
imgpof = pygame.image.load('images/pof1.png').convert_alpha()
imgpof2 = pygame.image.load('images/pof2.png').convert_alpha()
machine_a_sous2 = pygame.image.load('images/machine_a_sous2.png').convert_alpha()
machine_a_sous1 = pygame.image.load('images/machine_a_sous1.png').convert_alpha()
blackjack2 = pygame.image.load('images/blackjack2.png').convert_alpha()
blackjack1 = pygame.image.load('images/blackjack1.png').convert_alpha()
face = pygame.image.load('Pile_ou_face/Piece face.png').convert_alpha()
pile = pygame.image.load('Pile_ou_face/Piece pile.png').convert_alpha()
face2 = pygame.image.load('Pile_ou_face/Piece face2.png').convert_alpha()
pile2 = pygame.image.load('Pile_ou_face/Piece pile2.png').convert_alpha()
icone = pygame.image.load('images/icone.png').convert_alpha()
paradis = pygame.image.load('images/Fonds d\'ecran/paradis.png').convert_alpha()
fleche_retour = pygame.image.load('images/Fleche_retour.png').convert_alpha()
fleche_retour2 = pygame.image.load('images/Fleche_retour2.png').convert_alpha()
bouton_play_bj = pygame.image.load('images/BoutonPlay1.png').convert_alpha()
bouton_play_bj2 = pygame.image.load('images/BoutonPlay2.png').convert_alpha()
bouton_stop_bj = pygame.image.load('images/BoutonStop1.png').convert_alpha()
bouton_stop_bj2 = pygame.image.load('images/BoutonStop2.png').convert_alpha()
maskot = pygame.image.load('images/maskot.png').convert_alpha()
fondbj = pygame.image.load('images/Fonds d\'ecran/fondbj.png').convert_alpha()
abel = pygame.image.load('images/abel.png').convert_alpha()
boutique1 = pygame.image.load('images/boutique1.png').convert_alpha()
boutique2 = pygame.image.load('images/boutique2.png').convert_alpha()
jeucombat1 = pygame.image.load('images/Jeu_combat3.png').convert_alpha()
jeucombat2 = pygame.image.load('images/Jeu_combat4.png').convert_alpha()
vodka1 = pygame.image.load('images/vodka1.png').convert_alpha()
vodka2 = pygame.image.load('images/Vodka2.png').convert_alpha()
alcool1 = pygame.image.load('images/Alcool1.png').convert_alpha()
alcool2 = pygame.image.load('images/Alcool2.png').convert_alpha()
whisky1 = pygame.image.load('images/Whisky1.png').convert_alpha()
whisky2 = pygame.image.load('images/Whisky2.png').convert_alpha()
biere1 = pygame.image.load('images/Bière1.png').convert_alpha()
biere2 = pygame.image.load('images/Bière2.png').convert_alpha()
effet_vodka = pygame.image.load('images/Caractéristiques/Caractéristiques Vodka.png').convert_alpha()
effet_biere = pygame.image.load('images/Caractéristiques/Caractéristiques Bière.png').convert_alpha()
effet_whisky = pygame.image.load('images/Caractéristiques/Caractéristiques Whisky.png').convert_alpha()
icone_assassin = pygame.image.load('images/AssassinIcone.png').convert_alpha()
icone_maehv = pygame.image.load('images/icone_maevh.png').convert_alpha()
icone_zendo = pygame.image.load('images/icone_zendo.png').convert_alpha()
icone_zukong = pygame.image.load('images/icone_zukong.png').convert_alpha()
icone_hero = pygame.image.load('images/icone_hero.png').convert_alpha()
icone_sw = pygame.image.load('images/icone_sw.png').convert_alpha()
icone_lancier = pygame.image.load('images/icone_lancier.png').convert_alpha()
icone_spirithero = pygame.image.load('images/icone_spirithero.png').convert_alpha()
icone_hsuku = pygame.image.load('images/icone_hsuku.png').convert_alpha()

pygame.display.set_icon(icone)